# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
# http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_db:
            entity:
                class: AppBundle:oUser
                property: email
        in_memory:
            memory:
             users:
              admin@optovichok.com:
               password: 'admin'
               roles: 'ROLE_ADMIN'
              company@optovichok.com:
               password: 'company'
               roles: 'ROLE_COMPANY'
              client@optovichok.com:
               password: 'client'
               roles: 'ROLE_CLIENT'
        ##fos_userbundle:
                    ##id: fos_user.user_provider.username
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\UserInterface: bcrypt
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
      #  oauth_token:                                   # Everyone can access the access token URL.
           #         pattern: ^/oauth/v2/token
              #      security: false
       # api:
                 #   pattern: ^/                                # All URLs are protected
                 #   fos_oauth: true                            # OAuth2 protected resource
                   # stateless: true                            # Do no set session cookies
                  #  anonymous: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                provider: in_db
            logout:
                path:   /logout